<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Url Shortener</title>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/4.2.0/normalize.min.css">
    <link rel="stylesheet" type="text/css" href="dist/css/style.min.css">
</head>

<body>
    <div id="app">
        <form>
            <input type="text" v-bind:style="input.style" v-bind:disabled="!input.enabled" v-bind:placeholder="input.placeHolderText" v-model="input.url">
            <button v-on:click.prevent="submitUrl" v-bind:disabled="!input.url">{{ button.text }}</button>
        </form>
    </div>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.26/vue.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vue-resource/0.9.3/vue-resource.js"></script>
    <script type="text/javascript" src="dist/js/main.js"></script>
</body>

</html>
