<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Url Shortener</title>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/4.2.0/normalize.min.css">
    <link rel="stylesheet" type="text/css" href="dist/css/style.min.css">
</head>

<body>
    <div id="app">
        <form>
            <input type="text" pattern="^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$" required v-el:input v-bind:style="input.style" v-model="input.url" v-bind:readonly="input.completed" v-bind:placeholder="input.placeHolderText">
            <button v-on:click.prevent="buttonHandler" v-bind:disabled="input.disabled">{{ button.text }}</button>
            <?php 
                print'<input type="hidden" name="'.$data['nameKey'].'" value="'.$data['name'].'">';
                print'<input type="hidden" name="'.$data['valueKey'].'" value="'.$data['value'] .'">';                
            ?>
        </form>
    </div>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.26/vue.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vue-resource/0.9.3/vue-resource.js"></script>
    <script type="text/javascript" src="dist/js/main.js"></script>
</body>

</html>
